### PR TITLE
Feature/add parse unit test

### PR DESCRIPTION
**Pull request by shanereetz**
## What:
Add unit tests to the parsing logic, and integrate Dave's algorithm for name parsing.

## Why:
From development on the B&R extension, and ultimately refactoring of this function, we may have discovered some bugs.

### CODE REVIEW

**Comment by shanereetz** [comment]
Question: is the variable format from PyADS significantly different, other than the : vs . after program names?

After bringing in our unit tests (and slightly adapting them to use . not : between program name and var, these tests are failing. It's not clear yet if this is because the variable format is different and the tests are not valid.
IMO that needs to be discovered before this merge and publishing the next version.
Screenshot 2024-07-24 095313

**Comment by Joshpolansky** [comment]
I don't understand how PyAds would affect the tests, the tests don't seem like they interact with pyads? It seems to me like it's just using the test and methods from the other repo 🤔

**Comment by Joshpolansky** [comment]
I wonder if pyads is throwing exception from not being able to connect and is causing the tests to fail?

**Comment by shanereetz** [comment]
They don't interact with PyADS in terms of a connection, correct. What I mean is perhaps the string variable name format ('MAIN.myStruct.myVar') is slightly different, particularly in regards to arrays Meaning, maybe the tests are expecting a format other than this parsing algorithm provides.

I've since integrated the new algorithm, so just to note the commit with the failing tests is https://github.com/loupeteam/Omniverse_Beckhoff_Bridge_Extension/pull/5/commits/d84386aaaf54efee687ef48f546a45596fc96cf7

The tests are failing for a few reasons, all unrelated to the connection or missing methods. These tests report a diff of expected vs actual if they fail. It's a bit long so I'll just paste a few here.

- `AttributeError: 'dict' object has no attribute 'extend'`
- `TypeError: list indices must be integers or slices, not str`
-  : correct: {'myArray': [None, None, {'myVar': 30}]}
|| actual: {'myArray[2]': {'myVar': 30}}

**Comment by Joshpolansky** [comment]
But isn't this using the parsing code pulled from the other repo?

**Comment by shanereetz** [comment]
> I've since integrated the new algorithm, so just to note the commit with the failing tests is [d84386a](https://github.com/loupeteam/Omniverse_Beckhoff_Bridge_Extension/commit/d84386aaaf54efee687ef48f546a45596fc96cf7)

It's a few commits back, see link above

**Comment by Joshpolansky** [comment]
> > I've since integrated the new algorithm, so just to note the commit with the failing tests is [d84386a](https://github.com/loupeteam/Omniverse_Beckhoff_Bridge_Extension/commit/d84386aaaf54efee687ef48f546a45596fc96cf7)
> 
> 
> 
> We also ran the tests against the old parsing code. It's a few commits back, see link above

The part I don't understand is what the difference is between this parser and test and the B&R one? I thought you pulled that parse and those tests. Why would there be any differences?

**Comment by Joshpolansky** [comment]
The only difference between B&R and beckhoff is that beckhoff is that beckhoff has no local variables. A local var just looks like a global because it doesn't have ":"

I'm guessing the "adaptation" was converting from task:var[] to just var[]. Maybe global array is broken there too? You should run the exact same failing tests in the other repo.

**Comment by shanereetz** [comment]
> The only difference between B&R and beckhoff is that beckhoff is that beckhoff has no local variables. A local var just looks like a global because it doesn't have ":"
> 
> I'm guessing the "adaptation" was converting from task:var[] to just var[]. Maybe global array is broken there too? You should run the exact same failing tests in the other repo.

The exact same tests that failed here, pass in the other repo.

Is `gVar` valid in Beckhoff? If not, that might be a case that works for B&R but not here, and those tests might need to be tweaked for this repo.

**Comment by Joshpolansky** [comment]
Is this still something to review and merge?

**Comment by shanereetz** [comment]
> Is this still something to review and merge?

Yes.

**Review by Joshpolansky — APPROVED** [review]

**Pull request merged**
